
server:  port: 28080
spring:  config:
    import:
      - classpath:/prop/common.properties      application:
    name: spring-boot-test  datasource:
    url: "jdbc:mysql://localhost:3306/edu?serverTimezone=Asia/Seoul"
    username: soohan01
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver